### ISSUE TITLE
Bug with the last boss - build 1.5.4

### ISSUE THREAD

**Issue by Felipefpl** [katriellucas/lecarde-2#62]
When i was going to fight the last boss again i couldnt face it, he was nowhere to be found. I only equipped the Lecarde Sword this time instead of Durandal. It was the only thing i did differently. I'm on Win10 x64. Below is a savegame with the game already cleared:
[MMFApplications.zip](https://github.com/user-attachments/files/18061309/MMFApplications.zip)

**Comment by Aceearly1993** [comment]
Detected the source of this issue is with the new auto save mechanic the game auto saved a pointer to last boss talk event where it shouldn't be and it's now fixed. Will be applied to next revision.

**Comment by Felipefpl** [comment]
Thanks for the fix. My old savegame will work with the new version?

**Comment by Aceearly1993** [comment]
check if the variable 175 at: 
[lcfbotoxvar]
in your save file is 0. if it's 1, manually change it to 0. Then old save will be OK to carry.

**Comment by Felipefpl** [comment]
Tested and it worked. Thank you for your help.

Edit: Btw, I saw your update in the commits, it updated the readme.md file but not other(s) file(s) who might be responsable for the problem. Is there a reason for it?

Also, i updated the other brazilian portuguese language file plus i fixed the english one too. Just waiting the submission of the PR to submit a new PR with those files.

**Comment by Aceearly1993** [comment]
The reason is the fixes that are emergency will be directly applied at the game's binary file in "releases" page.

For Brazilian portuguese translation it's currently in discussion which may take longer than you would expect depending on if one of the translators "ThePlotTwist" is having good network or free time. In the end some of the changes for very long sentences (story cutscene dialogue, text box etc..) in your version will most likely be rejected or not 1:1 using your version due to 1) the fear of any technical problem to them at DX11 version (which used a different font than vanilla DX9 to make sure it's compatible with DX11) if some sentences ended up way too long for text box to handle in DX11 and 2) "ThePlotTwist", one of the Brazilian translators at the rework team had different opinion than yours. But we will see what the rework team says.

**Comment by Felipefpl** [comment]
> The reason is the fixes that are emergency will be directly applied at the game's binary file in "releases" page.

Oh, ok.

> For Brazilian portuguese translation it's currently in discussion which may take longer than you would expect depending on if one of the translators "ThePlotTwist" is having good network or free time. In the end some of the changes for very long sentences (story cutscene dialogue, text box etc..) in your version will most likely be rejected or not 1:1 using your version due to 1) the fear of any technical problem to them at DX11 version (which used a different font than vanilla DX9 to make sure it's compatible with DX11) if some sentences ended up way too long for text box to handle in DX11 and 2) "ThePlotTwist", one of the Brazilian translators at the rework team had different opinion than yours. But we will see what the rework team says.

Ok then.
